import AppChrome, { BackLink } from "@/components/AppChrome";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { formatArabicDate, formatDzd } from "@/lib/marketplace";
import { trpc } from "@/lib/trpc";
import { Heart, LogIn, PackageSearch, UserRound } from "lucide-react";

export default function Account() {
  const { user, loading } = useAuth();
  const requests = trpc.requests.mine.useQuery(undefined, { enabled: !!user });
  const favorites = trpc.account.favorites.useQuery(undefined, { enabled: !!user });
  if (loading) return <AppChrome><div className="container py-20 text-center text-sm text-slate-500">جارٍ التحقق من الحساب...</div></AppChrome>;
  if (!user) return <AppChrome><section className="container grid min-h-[55vh] place-items-center py-12"><div className="max-w-md rounded-[28px] border border-[#e6dfd1] bg-white p-8 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#eaf3ed] text-[#0a6e53]"><LogIn size={22} /></span><h1 className="mt-5 font-display text-3xl font-extrabold text-[#153e32]">ادخل لمتابعة طلباتك</h1><p className="mt-3 text-sm leading-7 text-slate-600">يسمح لك الحساب بحفظ العروض ومتابعة الطلبات التي أنشأتها. لا نخزن كلمة مرور في المنصة.</p><button onClick={startLogin} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#064e3b] px-5 py-3.5 text-sm font-extrabold text-white">تسجيل الدخول <LogIn size={16} /></button></div></section></AppChrome>;
  return <AppChrome><section className="container py-10 sm:py-14"><BackLink href="/" label="العودة للرئيسية" /><div className="mt-7 flex items-center gap-4"><span className="grid h-13 w-13 place-items-center rounded-2xl bg-[#e8f3eb] text-[#0b7257]"><UserRound size={24} /></span><div><h1 className="font-display text-3xl font-extrabold text-[#153e32]">حسابي</h1><p className="text-sm text-slate-600">{user.name || "مستخدم رفيق المعتمر"}</p></div></div><div className="mt-9 grid gap-6 lg:grid-cols-2"><section className="rounded-[26px] border border-[#e6e0d4] bg-white p-6"><h2 className="flex items-center gap-2 font-display text-2xl font-extrabold text-[#173f34]"><PackageSearch size={20} /> طلباتي</h2>{requests.data?.length ? <div className="mt-5 space-y-3">{requests.data.map(item => <div key={item.id} className="rounded-2xl bg-[#f5f6f1] p-4 text-sm"><b className="block text-[#264b3f]">طلب من {item.wilaya}</b><span className="mt-1 block text-slate-600">ميزانية {formatDzd(item.budgetDzd)} · {formatArabicDate(item.createdAt)}</span><span className="mt-2 inline-block rounded-full bg-white px-2 py-1 text-xs font-bold text-[#557166]">{item.status}</span></div>)}</div> : <Empty text="لا توجد طلبات محفوظة بعد. يمكنك إنشاء طلب عمرة من الصفحة الرئيسية." />}</section><section className="rounded-[26px] border border-[#e6e0d4] bg-white p-6"><h2 className="flex items-center gap-2 font-display text-2xl font-extrabold text-[#173f34]"><Heart size={20} /> العروض المحفوظة</h2>{favorites.data?.length ? <div className="mt-5 space-y-3">{favorites.data.map(item => <div key={item.offerId} className="rounded-2xl bg-[#f5f6f1] p-4 text-sm"><b className="block text-[#264b3f]">{item.title}</b><span className="mt-1 block text-slate-600">{item.agencyName} · {formatDzd(item.priceDzd)}</span></div>)}</div> : <Empty text="لا توجد عروض محفوظة. عند توفر العروض يمكنك إضافتها إلى قائمتك." />}</section></div></section></AppChrome>;
}
function Empty({ text }: { text: string }) { return <p className="mt-5 rounded-2xl bg-[#f5f6f1] p-4 text-sm leading-7 text-slate-600">{text}</p>; }
