import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Building2, FileCheck2, ShieldCheck, UsersRound } from "lucide-react";

export default function AdminDashboard() {
  const { user } = useAuth();
  const snapshot = trpc.admin.snapshot.useQuery(undefined, { enabled: user?.role === "admin" || user?.role === "super_admin" });
  const agencies = trpc.admin.agencies.useQuery(undefined, { enabled: user?.role === "admin" || user?.role === "super_admin" });
  const verify = trpc.admin.setAgencyVerification.useMutation({ onSuccess: () => { snapshot.refetch(); agencies.refetch(); } });
  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-6xl p-2 sm:p-6"><p className="text-xs font-bold tracking-[.16em] text-[#a17c34]">إدارة المنصة</p><h1 className="mt-2 font-display text-3xl font-extrabold text-[#153e32]">مراجعة تشغيل Marketplace</h1><p className="mt-2 text-sm leading-7 text-slate-600">لا تعرض المؤشرات إلا البيانات المسجلة في قاعدة المنصة، وتسجل إجراءات التحقق في سجل التدقيق.</p>{snapshot.isError && <p className="mt-6 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">هذه الصفحة متاحة للإدارة فقط.</p>}{snapshot.data && <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["إجمالي الوكالات",snapshot.data.agencies,Building2],["وكالات متحققة",snapshot.data.verifiedAgencies,ShieldCheck],["قيد المراجعة",snapshot.data.pendingAgencies,FileCheck2],["عروض نشطة",snapshot.data.activeOffers,FileCheck2],["Leads",snapshot.data.leads,UsersRound]].map(([label,value,Icon]) => { const I = Icon as typeof Building2; return <div key={label as string} className="rounded-2xl border bg-white p-4"><I size={18} className="text-[#0b7257]" /><p className="mt-3 text-xs font-bold text-slate-500">{label as string}</p><b className="mt-1 block text-2xl text-[#173e33]" dir="ltr">{String(value)}</b></div>})}</div>}<section className="mt-7 rounded-[24px] border bg-white p-5 sm:p-6"><h2 className="font-display text-xl font-extrabold text-[#153e32]">مراجعة الوكالات</h2>{agencies.data?.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-right text-sm"><thead className="text-xs text-slate-500"><tr><th className="pb-3">الوكالة</th><th className="pb-3">المدينة</th><th className="pb-3">الحالة</th><th className="pb-3">إجراء</th></tr></thead><tbody>{agencies.data.map(agency => <tr key={agency.id} className="border-t border-[#efede5]"><td className="py-4"><b className="block text-[#25473d]">{agency.displayName}</b><small className="text-slate-500">{agency.ownerEmail || "بريد غير منشور"}</small></td><td className="py-4 text-slate-600">{agency.city || "—"}</td><td className="py-4 text-slate-600">{agency.verificationStatus}</td><td className="py-4"><div className="flex gap-2"><button onClick={() => verify.mutate({ agencyId: agency.id, status: "verified" })} className="rounded-lg bg-[#eaf5eb] px-3 py-2 text-xs font-bold text-[#087057]">تحقق</button><button onClick={() => verify.mutate({ agencyId: agency.id, status: "rejected" })} className="rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">رفض</button></div></td></tr>)}</tbody></table></div> : <p className="mt-5 rounded-2xl bg-[#f5f6f1] p-4 text-sm text-slate-600">لا توجد وكالات للمراجعة حتى الآن.</p>}</section></div></DashboardLayout>;
}
