/**
 * Style reminder — "رحلات من نور": a premium B2B editorial page that frames monetization as useful infrastructure,
 * using deep-green authority, sand-gold conversion accents, and complete transparency about demo data and payments.
 */
import AppChrome, { SectionIntro } from "@/components/AppChrome";
import { BadgeCheck, BarChart3, Bot, Check, Crown, Layers3, Megaphone, MousePointerClick, Send, ShieldCheck, Sparkles, Target, UsersRound } from "lucide-react";
import { toast } from "sonner";

const plans = [
  { name: "Free", price: "0", description: "حضور أساسي وبداية منظمة", items: ["ملف وكالة تجريبي", "عرض واحد", "استقبال Leads محدود"], tone: "bg-white border-[#e6e1d5] text-[#183f34]", button: "border border-[#d6d0c0] bg-white text-[#274d42]" },
  { name: "Pro", price: "3,000", description: "نمو منظم لبرنامجك الشهري", items: ["عروض غير محدودة", "ظهور أفضل في الدليل", "إحصاءات وتحليل Leads", "مساعد تسويق AI"], tone: "bg-[#073f31] border-[#073f31] text-white", button: "bg-[#d6b878] text-[#193e33]" },
  { name: "Premium", price: "7,000", description: "حضور مميز للحملات المهمة", items: ["شارة موثوق تجريبية", "أولوية في النتائج", "مواضع إعلانية معلّمة", "تحليلات متقدمة"], tone: "bg-[#fff9e8] border-[#e5cb89] text-[#183f34]", button: "bg-[#064e3b] text-white" },
];

export default function AgencyGrowth() {
  return <AppChrome>
    <section className="relative isolate overflow-hidden bg-[#f8f0d9] py-14 text-[#193e33] sm:py-20"><div className="absolute left-[-12rem] top-[-9rem] h-[30rem] w-[30rem] rounded-full border border-[#d6b878]/45" /><div className="absolute bottom-[-12rem] right-[8%] h-[25rem] w-[25rem] rounded-full bg-[#d6b878]/25 blur-3xl" /><div className="container relative grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><span className="inline-flex items-center gap-2 rounded-full border border-[#d6b878] bg-white/70 px-3 py-1.5 text-xs font-extrabold text-[#785719]"><Sparkles size={14} /> بنية نمو للوكالات</span><h1 className="mt-6 max-w-2xl font-display text-4xl font-extrabold leading-[1.2] sm:text-5xl">حوّل ظهور وكالتك إلى <span className="text-[#9a7024]">فرص تواصل أوضح.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-[#4f655a]">رفيق المعتمر AI يقدّم نموذجًا عمليًا لعرض برامجك، قياس الاهتمام، وإبراز حملاتك بوضوح من دون تشويش تجربة المعتمر.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={() => toast.info("طلب الانضمام جزء من نموذج الواجهة؛ لا تُرسل بيانات في هذه النسخة.")} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#064e3b] px-5 py-4 text-sm font-extrabold text-white transition hover:-translate-y-0.5"><Send size={17} /> اطلب عرضًا لوكالتك</button><button onClick={() => toast.info("إضافة برنامج ستكون متاحة بعد تفعيل حساب الوكالة.")} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-[#b69a57] bg-white/50 px-5 py-4 text-sm font-bold text-[#264d41]">شاهد نموذج لوحة الوكالة</button></div></div><div className="relative overflow-hidden rounded-[32px] bg-[#064e3b] p-5 shadow-[0_20px_48px_rgba(6,78,59,.2)]"><span className="pointer-events-none absolute -right-20 -top-14 h-40 w-72 rounded-[100%] border border-[#d6b878]/50" /><div className="grid gap-3 sm:grid-cols-2"><Metric icon={UsersRound} value="86" label="Lead تجريبي هذا الشهر" /><Metric icon={MousePointerClick} value="12.4K" label="مشاهدة لبرامج الوكالة" /><Metric icon={Target} value="6.9%" label="نسبة تحويل افتراضية" /><Metric icon={BarChart3} value="+18%" label="نمو اهتمام المحتوى" /></div></div></div></section>
    <section className="container py-16 sm:py-20"><SectionIntro eyebrow="مسارات ربح متوازنة" title="ثلاث طبقات تجارية، في واجهة تحترم المستخدم" body="نموذج الإيراد مصمم ليجعل الوكالة أكثر ظهورًا عندما يقدم ذلك قيمة للمسافر، وبإشارة صريحة عند أي محتوى مدعوم." /><div className="grid gap-5 lg:grid-cols-3"><RevenueCard icon={UsersRound} title="عملاء محتملون منظّمون" text="تلتقط المنصة طلبات التواصل بعد أن يحدد المعتمر ميزانيته واهتمامه، ثم تعرضها للوكالة ضمن لوحة واحدة." tag="Lead generation" /><RevenueCard icon={Megaphone} title="ظهور مدعوم بوضوح" text="مواضع مميزة داخل دليل الوكالات أو نتائج العروض، تحمل وسم «محتوى مدعوم» ولا تغيّر ترتيب التوصيات الذكية." tag="Sponsored placement" accent /><RevenueCard icon={Layers3} title="اشتراكات للوكالات" text="باقات شهرية للوصول إلى أدوات الإحصاء ورفع العروض وإدارة العملاء المحتملين والمساعد التسويقي." tag="SaaS subscription" /></div></section>
    <section className="bg-[#eff4ef] py-16 sm:py-20"><div className="container"><SectionIntro eyebrow="باقات تجريبية" title="اختر حضورًا يناسب مرحلة وكالتك" body="تُعرض الأسعار كمثال للتصميم فقط، ولا توجد عملية دفع أو اشتراك فعلي في النسخة الحالية." /><div className="grid gap-5 lg:grid-cols-3">{plans.map((plan) => <article key={plan.name} className={`relative rounded-[28px] border p-7 ${plan.tone}`}>{plan.name === "Pro" && <span className="absolute -top-3 right-6 rounded-full bg-[#d6b878] px-3 py-1.5 text-xs font-extrabold text-[#183e33]">الأكثر توازنًا</span>}<p className="text-sm font-bold text-inherit opacity-70">{plan.name}</p><div className="mt-4 flex items-end gap-1"><span className="font-display text-4xl font-extrabold" dir="ltr">{plan.price}</span><span className="pb-1 text-sm font-bold">دج / شهر</span></div><p className="mt-4 text-sm leading-7 opacity-80">{plan.description}</p><ul className="mt-6 space-y-3">{plan.items.map((item) => <li key={item} className="flex gap-2 text-sm"><Check size={17} className="mt-0.5 shrink-0 text-[#d6b878]" />{item}</li>)}</ul><button onClick={() => toast.info(`باقة ${plan.name} معروضة لأغراض النموذج فقط.`)} className={`mt-8 w-full rounded-xl px-4 py-3.5 text-sm font-extrabold transition hover:-translate-y-0.5 ${plan.button}`}>اختيار الباقة التجريبية</button></article>)}</div></div></section>
    <section className="container py-16 sm:py-20"><div className="grid gap-7 rounded-[32px] border border-[#e3dcc9] bg-[#fffdf7] p-7 sm:p-10 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-xs font-extrabold tracking-[.18em] text-[#a0782e]">مبدأ الثقة</p><h2 className="mt-3 font-display text-3xl font-extrabold leading-tight text-[#133d32]">الإعلان يعمل عندما يكون واضحًا، ونافعًا، وقابلًا للقياس.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-600">لا يُقدّم أي محتوى مدعوم على أنه توصية شخصية من الذكاء الاصطناعي. تبقى التوصيات مرتبطة باختيارات المعتمر، بينما تحصل الوكالة على مؤشرات مفهومة لاتخاذ قرار تسويقي أفضل.</p></div><div className="grid gap-3"><Trust icon={BadgeCheck} title="وسم صريح للمحتوى المدعوم" text="حماية ثقة المسافر من البداية." /><Trust icon={ShieldCheck} title="معلومات قبل التواصل" text="الوكالة ترى سبب الاهتمام، لا مجرد رقم." /><Trust icon={Bot} title="مسودات تسويقية أسرع" text="عنوان ووصف ونسخ قنوات تواصل من تفاصيل العرض." /></div></div></section>
  </AppChrome>;
}

function Metric({ icon: Icon, value, label }: { icon: typeof UsersRound; value: string; label: string }) { return <div className="rounded-[23px] border border-white/15 bg-white/[.07] p-5 text-white backdrop-blur"><Icon size={20} className="text-[#e4c779]" /><b className="mt-5 block font-display text-3xl" dir="ltr">{value}</b><span className="mt-1 block text-xs leading-5 text-[#cfe0d7]">{label}</span></div> }
function RevenueCard({ icon: Icon, title, text, tag, accent = false }: { icon: typeof UsersRound; title: string; text: string; tag: string; accent?: boolean }) { return <article className={`rounded-[26px] border p-6 ${accent ? "border-[#e5ce8e] bg-[#fff8e6]" : "border-[#e8e2d6] bg-white"}`}><span className={`grid h-11 w-11 place-items-center rounded-2xl ${accent ? "bg-[#d6b878] text-[#193e33]" : "bg-[#edf5ee] text-[#0a7257]"}`}><Icon size={20} /></span><p className="mt-6 text-[11px] font-extrabold tracking-[.16em] text-[#a0782e]">{tag}</p><h3 className="mt-2 font-display text-2xl font-extrabold text-[#173f34]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></article> }
function Trust({ icon: Icon, title, text }: { icon: typeof BadgeCheck; title: string; text: string }) { return <div className="flex gap-3 rounded-2xl bg-[#f1f5f0] p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white text-[#0a7257]"><Icon size={18} /></span><span><b className="block text-sm text-[#24483d]">{title}</b><small className="mt-1 block text-xs leading-5 text-slate-500">{text}</small></span></div> }
