/**
 * Style reminder — "رحلات من نور": agency discovery feels like a composed editorial directory;
 * expressive but restrained marks and clear trust labels keep fictional entities visibly provisional.
 */
import AppChrome, { SectionIntro } from "@/components/AppChrome";
import { agencies } from "@/lib/mockData";
import { BadgeCheck, ChevronDown, MapPin, SlidersHorizontal, Star } from "lucide-react";
import { toast } from "sonner";

export default function Agencies() {
  return <AppChrome><section className="container py-12 sm:py-16"><SectionIntro eyebrow="دليل الوكالات التجريبي" title="وكالات العمرة" body="استكشف كيف يمكن لملفات الوكالات المنظمة أن تساعدك على الوصول إلى البرامج المناسبة. أسماء الوكالات أدناه افتراضية للتصميم." /><div className="mb-8 grid gap-3 rounded-[22px] border border-[#e4dfd2] bg-white p-3 md:grid-cols-4">{["الولاية", "السعر", "التقييم", "نوع البرامج"].map((item) => <button key={item} className="flex items-center justify-between rounded-xl bg-[#f4f5f0] px-4 py-3 text-sm font-bold text-[#466158]">{item}<ChevronDown size={16} /></button>)}<button className="flex items-center justify-center gap-2 rounded-xl bg-[#064e3b] px-4 py-3 text-sm font-bold text-white"><SlidersHorizontal size={16} /> تطبيق</button></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{agencies.map((agency) => <article key={agency.name} className="rounded-[25px] border border-[#e7e2d6] bg-white p-5 transition hover:-translate-y-1 hover:border-[#d6b878] hover:shadow-[0_18px_36px_rgba(27,58,44,.09)]"><div className="flex items-start justify-between"><span className={`grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br ${agency.tone} font-display text-xl font-extrabold text-white shadow-sm`}>{agency.initials}</span><span className="flex items-center gap-1 rounded-full bg-[#fff7e5] px-2.5 py-1 text-xs font-bold text-[#986f22]"><Star size={13} fill="currentColor" />{agency.rating}</span></div><h2 className="mt-5 font-display text-xl font-extrabold text-[#193f34]">{agency.name}</h2><p className="mt-2 flex items-center gap-1 text-sm text-slate-500"><MapPin size={15} className="text-[#a98138]" />{agency.city}</p><div className="mt-5 flex items-center justify-between border-t border-[#eee9df] pt-4"><span className="inline-flex items-center gap-1 text-xs font-bold text-[#0e7156]"><BadgeCheck size={15} />وكالة موثقة <small className="text-slate-400">(تصميميًا)</small></span><span className="text-xs text-slate-500">{agency.offers} عروض</span></div><button onClick={() => toast.info("هذه الوكالة تجريبية؛ صفحة العروض قيد العرض التصميمي.")} className="mt-5 w-full rounded-xl bg-[#eef4ee] py-3 text-sm font-bold text-[#1b5b48] transition hover:bg-[#dfece1]">عرض العروض</button></article>)}</div></section></AppChrome>;
}
