/**
 * Style reminder — "رحلات من نور": this home page uses an asymmetric Makkah hero and a flowing route
 * from reassurance to action, with large Arabic type and sand-gold highlights instead of generic cards.
 */
import AppChrome, { RouteTicket, SectionIntro } from "@/components/AppChrome";
import OfferCard from "@/components/OfferCard";
import { agencies, offers } from "@/lib/mockData";
import { Link } from "wouter";
import { ArrowLeft, BadgeCheck, Bot, Building2, Check, ChevronLeft, Compass, HeartHandshake, Hotel, Search, ShieldCheck, Sparkles, Star, Waypoints } from "lucide-react";

const heroImage = "/manus-storage/rafiq-hero-makkah-1920_6b7b1569.webp";
const mobileHeroImage = "/manus-storage/rafiq-hero-makkah-960_e5731638.webp";

export default function Home() {
  return <AppChrome>
    <section className="relative isolate overflow-hidden bg-[#0a4537] text-white">
      <picture className="absolute inset-0 -z-20"><source media="(max-width: 767px)" srcSet={mobileHeroImage} /><img src={heroImage} alt="المسجد الحرام وقت الغروب" width="1920" height="1080" decoding="async" fetchPriority="high" className="h-full w-full object-cover object-center" /></picture>
      <div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(3,43,33,.98)_5%,rgba(3,43,33,.85)_38%,rgba(5,58,43,.38)_68%,rgba(3,25,19,.25))]" />
      <div className="absolute -left-28 top-16 -z-10 h-72 w-72 rounded-full border border-[#d6b878]/30" />
      <div className="container grid min-h-[625px] items-center gap-12 py-14 lg:grid-cols-[.9fr_1.1fr] lg:py-20">
        <div className="max-w-xl">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#d6b878]/45 bg-[#113d33]/65 px-3 py-1.5 text-xs font-bold text-[#f8e9bd]"><Sparkles size={14} /> اختيار أوضح لرحلة العمر</div>
          <h1 className="font-display text-5xl font-extrabold leading-[1.1] tracking-tight sm:text-6xl">عمرتك<br /><span className="text-[#ead290]">تبدأ من هنا</span></h1>
          <p className="mt-6 max-w-lg text-base leading-8 text-[#e4ece7] sm:text-lg">دع الذكاء الاصطناعي يساعدك في العثور على العرض الأنسب لميزانيتك واحتياجاتك، خطوة بخطوة وبلا تعقيد.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/planner" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#d6b878] px-5 py-4 text-sm font-extrabold text-[#163b31] transition hover:-translate-y-0.5 hover:bg-[#edcf88]"><Bot size={19} /> اكتشف عمرتي بالذكاء الاصطناعي</Link><Link href="/offers" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/35 bg-white/5 px-5 py-4 text-sm font-bold text-white backdrop-blur transition hover:bg-white/15">استكشف عروض العمرة <ArrowLeft size={17} /></Link></div>
          <div className="mt-10 flex flex-wrap gap-x-5 gap-y-3 text-xs font-semibold text-[#edf5ef]"><span className="flex items-center gap-1.5"><Check size={14} className="text-[#e1c06d]" />عروض منشورة مع المصدر</span><span className="flex items-center gap-1.5"><Check size={14} className="text-[#e1c06d]" />تحقق بتاريخ 21 أغسطس</span><span className="flex items-center gap-1.5"><Check size={14} className="text-[#e1c06d]" />دون ادعاء توفر مضمون</span></div>
        </div>
        <div className="hidden justify-self-end lg:block"><div className="w-[330px] rotate-[2deg] rounded-[28px] border border-white/30 bg-[#fdfcf8]/95 p-5 text-[#163e33] shadow-2xl backdrop-blur"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#9a7430]">توصية مبدئية</span><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#eaf4ed]"><Compass size={18} /></span></div><p className="mt-4 font-display text-2xl font-extrabold">نرتب الخيارات حولك، لا العكس.</p><p className="mt-2 text-sm leading-6 text-slate-600">ابدأ بثلاث دقائق من الأسئلة البسيطة، ثم شاهد الخيارات الأقرب لاحتياجاتك.</p><div className="mt-5 rounded-2xl bg-[#eef5ef] p-3"><RouteTicket route="الجزائر ← جدة" duration="10 أيام" /></div></div></div>
      </div>
    </section>

    <section className="relative overflow-hidden bg-[#fbfaf7] py-20"><div className="absolute right-[8%] top-20 h-48 w-48 rounded-full border border-[#d6b878]/35" /><div className="container relative"><SectionIntro eyebrow="من الحيرة إلى الوضوح" title="كيف يعمل رفيق المعتمر؟" body="أسئلة قصيرة، قراءة أذكى للاحتياجات، ثم مقارنة تستطيع فهمها من النظرة الأولى." /><div className="grid gap-5 md:grid-cols-4">{[["01", "أخبرنا بما تحتاج", "المدينة، الميزانية، عدد المسافرين وما يهمك."], ["02", "نحلل اختياراتك", "نرتب الأولويات عبر مخطط بسيط وهادئ."], ["03", "نقارن أفضل الخيارات", "السعر والفندق والمدة والنقل في مكان واحد."], ["04", "تواصل عندما تكون جاهزًا", "تفاصيل واضحة وخطوة تواصل مباشرة مع الوكالة."]].map(([number, title, body]) => <div key={number} className="group relative rounded-[24px] bg-white p-6 shadow-[0_10px_28px_rgba(29,51,40,.05)]"><span className="font-display text-5xl font-extrabold text-[#e9e1ce] transition group-hover:text-[#d6b878]">{number}</span><h3 className="mt-7 font-display text-lg font-extrabold text-[#164235]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></div>)}</div></div></section>

    <section className="bg-[#edf3ee] py-20"><div className="container"><SectionIntro eyebrow="تحقق مصدرّي · 21 أغسطس 2026" title="عروض عمرة منشورة حاليًا" body="أسعار ومدن انطلاق ومدد ظاهرة في المصدر الأصلي. راجع التفاصيل والتوفر عبر الرابط قبل أي تواصل أو حجز." action={<Link href="/offers" className="inline-flex items-center gap-1 text-sm font-extrabold text-[#0b7256]">كل العروض والمصادر <ChevronLeft size={16} /></Link>} /><div className="grid gap-5 lg:grid-cols-3">{offers.slice(0, 3).map((offer, index) => <OfferCard key={offer.id} offer={offer} featured={index === 0} />)}</div></div></section>

    <section className="container py-20"><div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[30px] bg-[#073f31] p-8 text-white sm:p-10"><p className="text-xs font-extrabold tracking-[.18em] text-[#e1c277]">ثقة تُرى في التفاصيل</p><h2 className="mt-4 max-w-xl font-display text-4xl font-extrabold leading-tight">لماذا رفيق المعتمر؟</h2><div className="mt-9 grid gap-5 sm:grid-cols-2">{[[ShieldCheck,"رابط المصدر ظاهر","كل سعر جديد يقترن برابط مباشر وتاريخ تحقق."],[HeartHandshake,"مصمم ليستعمله الجميع","خط عربي واضح، أزرار كبيرة، وخطوات قليلة ومباشرة."],[Waypoints,"مقارنة على قدر المتاح","نظهر ما نشره المصدر، ونُبقي الحقول غير الظاهرة بلا افتراض."],[BadgeCheck,"شفافية مصدرية","ظهور العرض لا يعني اعتمادًا أو شراكة أو ضمان توفر."]].map(([Icon, title, body]) => { const IconComponent = Icon as typeof ShieldCheck; return <div key={title as string} className="rounded-2xl border border-white/10 bg-white/5 p-4"><IconComponent className="text-[#e2c273]" size={22} /><h3 className="mt-4 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[#c9d8d0]">{body as string}</p></div>})}</div></div><div className="flex flex-col justify-center"><p className="text-xs font-extrabold tracking-[.18em] text-[#a78038]">وكالات في النموذج</p><h2 className="mt-3 font-display text-3xl font-extrabold text-[#153d32]">وكالات تظهر بصورة أكثر احترافية</h2><p className="mt-3 max-w-md text-sm leading-7 text-slate-600">لوحة خاصة للوكالة تجمع العروض، العملاء المحتملين، والإحصاءات، مع فكرة تسويقية مدعومة بالذكاء الاصطناعي.</p><div className="mt-6 space-y-3">{agencies.slice(0, 3).map((agency) => <Link href="/agencies" key={agency.name} className="flex items-center justify-between rounded-2xl border border-[#e7e1d3] bg-white p-4 transition hover:border-[#d6b878]"><div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br ${agency.tone} text-sm font-extrabold text-white`}>{agency.initials}</span><span><b className="block text-sm text-[#26483e]">{agency.name}</b><small className="text-xs text-slate-500">{agency.city} · {agency.offers} عروض</small></span></div><span className="flex items-center gap-1 text-xs font-bold text-[#9b762d]"><Star size={13} fill="currentColor" />{agency.rating}</span></Link>)}</div><Link href="/agency-dashboard" className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-[#0b7256]">استكشف لوحة الوكالة <ArrowLeft size={16} /></Link></div></div></section>

    <section className="container py-8 sm:py-12"><div className="relative overflow-hidden rounded-[32px] bg-[#fff9e9] p-7 shadow-[0_18px_48px_rgba(92,67,16,.08)] sm:p-10"><div className="absolute -left-20 -top-20 h-60 w-60 rounded-full border border-[#d6b878]/45" /><div className="relative grid items-center gap-7 lg:grid-cols-[1.06fr_.94fr]"><div><span className="inline-flex items-center gap-2 rounded-full bg-[#f0dfad] px-3 py-1.5 text-xs font-extrabold text-[#6c4c11]"><Building2 size={14} /> للوكالات وشركاء السفر</span><h2 className="mt-4 max-w-2xl font-display text-3xl font-extrabold leading-tight text-[#173d32]">ظهور أذكى لوكالتك. وطلبات تواصل أكثر وضوحًا.</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[#5b645b]">مساحة احترافية لعرض برامجك، قياس الاهتمام، واستثمار ظهور مدعوم معلّن بوضوح دون إرباك تجربة المعتمر.</p><Link href="/agency-growth" className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-[#064e3b] px-5 py-3.5 text-sm font-extrabold text-white transition hover:-translate-y-0.5">اكتشف حلول الوكالات <ArrowLeft size={17} /></Link></div><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-1">{[["86","Leads تجريبية"],["12.4K","مشاهدة برامج"],["6.9%","تحويل افتراضي"]].map(([value,label]) => <div key={label} className="flex items-center justify-between rounded-2xl border border-[#e8d5a0] bg-white/80 p-4"><b className="font-display text-2xl font-extrabold text-[#12543f]" dir="ltr">{value}</b><span className="text-xs font-bold text-[#726047]">{label}</span></div>)}</div></div></div></section>
    <section className="container pb-8"><div className="overflow-hidden rounded-[32px] bg-[#d8bd80] px-7 py-10 sm:px-12"><div className="grid items-center gap-6 md:grid-cols-[1fr_auto]"><div><p className="text-xs font-extrabold tracking-[.18em] text-[#684d1d]">خطوتك الأولى</p><h2 className="mt-3 font-display text-4xl font-extrabold leading-tight text-[#153c31]">ابدأ تخطيط عمرتك الآن</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[#315146]">من أين ستسافر؟ كم عددكم؟ وما الذي يجعل الرحلة مناسبة لك؟ أجب ببساطة، وسنرتب لك نقطة بداية.</p></div><Link href="/planner" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#064e3b] px-6 py-4 text-sm font-extrabold text-white shadow-lg transition hover:-translate-y-0.5"><Sparkles size={18} /> ابدأ التخطيط الذكي</Link></div></div></section>
  </AppChrome>;
}
