import AppChrome, { RouteTicket, SectionIntro } from "@/components/AppChrome";
import OfferCard from "@/components/OfferCard";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";
import { ArrowLeft, BadgeCheck, Bot, Building2, Check, Compass, HeartHandshake, Landmark, Search, ShieldCheck, Sparkles, Waypoints } from "lucide-react";

const heroImage = "/manus-storage/rafiq-hero-makkah-1920_6b7b1569.webp";
const mobileHeroImage = "/manus-storage/rafiq-hero-makkah-960_e5731638.webp";

export default function Home() {
  const { data: offers } = trpc.offers.list.useQuery({ limit: 3, featuredOnly: true });
  const { data: agencies } = trpc.agencies.list.useQuery({ limit: 3 });
  return <AppChrome><section className="relative isolate overflow-hidden bg-[#0a4537] text-white"><picture className="absolute inset-0 -z-20"><source media="(max-width: 767px)" srcSet={mobileHeroImage} /><img src={heroImage} alt="المسجد الحرام وقت الغروب" width="1920" height="1080" decoding="async" fetchPriority="high" className="h-full w-full object-cover object-center" /></picture><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(3,43,33,.98)_5%,rgba(3,43,33,.85)_38%,rgba(5,58,43,.38)_68%,rgba(3,25,19,.25))]" /><div className="container grid min-h-[625px] items-center gap-12 py-14 lg:grid-cols-[.9fr_1.1fr] lg:py-20"><div className="max-w-xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#d6b878]/45 bg-[#113d33]/65 px-3 py-1.5 text-xs font-bold text-[#f8e9bd]"><Sparkles size={14} /> Marketplace عمرة مبني على الوضوح</div><h1 className="font-display text-5xl font-extrabold leading-[1.1] tracking-tight sm:text-6xl">عمرتك<br /><span className="text-[#ead290]">تبدأ من هنا</span></h1><p className="mt-6 max-w-lg text-base leading-8 text-[#e4ece7] sm:text-lg">ابحث، قارن، وأرسل طلبًا واضحًا لوكالات ضمن المنصة. يساعدك الترتيب الذكي في قراءة ما نُشر من دون اختراع تفاصيل أو توفر.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/planner" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#d6b878] px-5 py-4 text-sm font-extrabold text-[#163b31]"><Bot size={19} /> ابدأ الترتيب الذكي</Link><Link href="/offers" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/35 bg-white/5 px-5 py-4 text-sm font-bold text-white backdrop-blur">استكشف العروض <ArrowLeft size={17} /></Link></div><div className="mt-10 flex flex-wrap gap-x-5 gap-y-3 text-xs font-semibold text-[#edf5ef]"><span className="flex items-center gap-1.5"><Check size={14} className="text-[#e1c06d]" />سعر وتاريخ تحديث ظاهر</span><span className="flex items-center gap-1.5"><Check size={14} className="text-[#e1c06d]" />حالة الوكالة داخل المنصة</span><span className="flex items-center gap-1.5"><Check size={14} className="text-[#e1c06d]" />لا حجز أو دفع خفي</span></div></div><div className="hidden justify-self-end lg:block"><div className="w-[330px] rotate-[2deg] rounded-[28px] border border-white/30 bg-[#fdfcf8]/95 p-5 text-[#163e33] shadow-2xl backdrop-blur"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#9a7430]">قرار قابل للفهم</span><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#eaf4ed]"><Compass size={18} /></span></div><p className="mt-4 font-display text-2xl font-extrabold">نرتب الخيارات حولك، لا العكس.</p><p className="mt-2 text-sm leading-6 text-slate-600">تحدد المدينة والميزانية والمدة ونمط الرحلة، ثم ترى سبب ترتيب كل عرض.</p><div className="mt-5 rounded-2xl bg-[#eef5ef] p-3"><RouteTicket route="الجزائر ← جدة" duration="وفق اختيارك" /></div></div></div></div></section>
    <section className="relative overflow-hidden bg-[#fbfaf7] py-20"><div className="container relative"><SectionIntro eyebrow="من الحيرة إلى الوضوح" title="كيف يعمل رفيق المعتمر؟" body="بحث متصل بعروض منشورة، ترتيب حتمي قابل للتفسير، ثم طلب واضح لا يُشارك إلا بموافقتك." /><div className="grid gap-5 md:grid-cols-4">{[["01", "حدّد احتياجك", "المدينة والميزانية والمدة وما يهمك."], ["02", "اقرأ المطابقة", "نظهر سبب الترتيب من بيانات العرض."], ["03", "قارن بهدوء", "السعر والمدة والخدمات في بطاقة واحدة."], ["04", "أرسل طلبك", "بياناتك لا تصل للوكالة قبل موافقتك."]].map(([number, title, body]) => <div key={number} className="rounded-[24px] bg-white p-6 shadow-[0_10px_28px_rgba(29,51,40,.05)]"><span className="font-display text-5xl font-extrabold text-[#e9e1ce]">{number}</span><h3 className="mt-7 font-display text-lg font-extrabold text-[#164235]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></div>)}</div></div></section>
    <section className="bg-[#edf3ee] py-20"><div className="container"><SectionIntro eyebrow="عروض متصلة بالمنصة" title="عروض نشطة من وكالات متحققة" body="تظهر العروض فقط بعد اعتمادها داخل المنصة. إذا كانت القائمة فارغة، فذلك يعني عدم وجود عروض منشورة مناسبة حاليًا." action={<Link href="/offers" className="inline-flex items-center gap-1 text-sm font-extrabold text-[#0b7256]">كل العروض <ArrowLeft size={16} /></Link>} />{offers && offers.length > 0 ? <div className="grid gap-5 lg:grid-cols-3">{offers.map((offer, index) => <OfferCard key={offer.id} offer={offer} featured={index === 0} />)}</div> : <div className="rounded-[26px] border border-dashed border-[#d7d2c2] bg-white p-8 text-sm leading-7 text-slate-600">لا توجد عروض نشطة مميزة الآن. <Link href="/request-umrah" className="font-bold text-[#0a7257]">أرسل طلب عمرة</Link> وسنحفظه في حسابك عند تسجيل الدخول.</div>}</div></section>
    <section className="container py-20"><div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[30px] bg-[#073f31] p-8 text-white sm:p-10"><p className="text-xs font-extrabold tracking-[.18em] text-[#e1c277]">ثقة تُرى في التفاصيل</p><h2 className="mt-4 max-w-xl font-display text-4xl font-extrabold leading-tight">لماذا رفيق المعتمر؟</h2><div className="mt-9 grid gap-5 sm:grid-cols-2">{[[ShieldCheck,"مصدر وسعر محدثان","نُظهر متى حدث السعر أو المصدر."],[HeartHandshake,"موافقة قبل المشاركة","لا نشارك رقم هاتف الطلب دون إقرار صريح."],[Waypoints,"ترتيب قابل للتفسير","لا نخفي سبب المطابقة خلف ادعاء ذكاء عام."],[BadgeCheck,"تحقق داخلي واضح","لا نخلط تحقق المنصة بالاعتماد الحكومي."]].map(([Icon, title, body]) => { const IconComponent = Icon as typeof ShieldCheck; return <div key={title as string} className="rounded-2xl border border-white/10 bg-white/5 p-4"><IconComponent className="text-[#e2c273]" size={22} /><h3 className="mt-4 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[#c9d8d0]">{body as string}</p></div>})}</div></div><div className="flex flex-col justify-center"><p className="text-xs font-extrabold tracking-[.18em] text-[#a78038]">للشركاء</p><h2 className="mt-3 font-display text-3xl font-extrabold text-[#153d32]">وكالتك في مكان أوضح</h2><p className="mt-3 max-w-md text-sm leading-7 text-slate-600">سجّل ملف وكالتك، أرسل عروضك للمراجعة، ثم تابع مؤشرات العروض والعملاء المحتملين من بياناتك الفعلية فقط.</p>{agencies && agencies.length > 0 ? <div className="mt-6 space-y-3">{agencies.map(agency => <Link href={`/agencies/${agency.slug}`} key={agency.id} className="flex items-center justify-between rounded-2xl border border-[#e7e1d3] bg-white p-4"><span><b className="block text-sm text-[#26483e]">{agency.displayName}</b><small className="text-xs text-slate-500">{agency.city || "المدينة غير منشورة"}</small></span><Landmark size={18} className="text-[#aa7c2b]" /></Link>)}</div> : <p className="mt-5 rounded-2xl bg-[#f3f4ef] p-4 text-sm text-slate-600">ستظهر هنا الوكالات بعد إكمال التحقق داخل المنصة.</p>}<Link href="/agency-growth" className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-[#0b7256]">تعرّف على حلول الوكالات <ArrowLeft size={16} /></Link></div></div></section>
    <section className="container pb-10"><div className="rounded-[32px] bg-[#d8bd80] px-7 py-10 sm:px-12"><div className="grid items-center gap-6 md:grid-cols-[1fr_auto]"><div><p className="text-xs font-extrabold tracking-[.18em] text-[#684d1d]">خطوتك الأولى</p><h2 className="mt-3 font-display text-4xl font-extrabold leading-tight text-[#153c31]">ابدأ طلب عمرتك الآن</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[#315146]">اكتب احتياجك بوضوح، واختر صراحة ما إذا كنت توافق على مشاركة بيانات التواصل مع وكالة مناسبة.</p></div><Link href="/request-umrah" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#064e3b] px-6 py-4 text-sm font-extrabold text-white shadow-lg"><Search size={18} /> أنشئ طلب عمرة</Link></div></div></section>
  </AppChrome>;
}
