/**
 * Style reminder — "رحلات من نور": knowledge content uses calm card rhythm and helpful language;
 * it signals official verification for sensitive religious information instead of fabricating guidance.
 */
import AppChrome, { SectionIntro } from "@/components/AppChrome";
import { knowledgeCards } from "@/lib/mockData";
import { ArrowLeft, BookOpenCheck, ChevronLeft, CircleAlert, FileText, Luggage, MapPinned } from "lucide-react";
import { toast } from "sonner";

const madinahImage = "/manus-storage/rafiq-madinah-guide-1280_8c8b5c68.webp";
const icons = [BookOpenCheck, Luggage, MapPinned, FileText];
export default function Knowledge() { return <AppChrome><section className="container py-12 sm:py-16"><div className="grid gap-8 lg:grid-cols-[1fr_.85fr]"><div><p className="text-xs font-extrabold tracking-[.18em] text-[#a47b31]">مركز المعرفة</p><h1 className="mt-4 font-display text-4xl font-extrabold leading-tight text-[#153e32] sm:text-5xl">دليل المعتمر،<br />بكلمات أبسط.</h1><p className="mt-5 max-w-xl text-base leading-8 text-slate-600">مساحة توضيحية لمقالات عملية تساعد على الاستعداد والتنظيم. لا يقدم هذا النموذج فتاوى أو أحكامًا دينية تفصيلية.</p><div className="mt-7 rounded-2xl border border-[#f0dfb6] bg-[#fff7e4] p-4 text-sm leading-7 text-[#755820]"><CircleAlert size={18} className="ml-2 inline" /> للمعلومات الدينية الحساسة أو التفصيلية، يُرجى التحقق من المصادر الرسمية أو العلماء الموثوقين.</div></div><div className="relative min-h-[280px] overflow-hidden rounded-[29px]"><img src={madinahImage} alt="المسجد النبوي في المدينة المنورة" width="1280" height="960" loading="lazy" decoding="async" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#102d25]/80 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-6 text-white"><span className="text-xs font-bold text-[#efd38c]">وجهة ودليل</span><h2 className="mt-2 font-display text-2xl font-extrabold">دليل المدينة</h2><button onClick={() => toast.info("هذه المقالة جزء من واجهة النموذج التجريبي.")} className="mt-3 inline-flex items-center gap-1 text-sm font-bold">اقرأ الدليل <ArrowLeft size={16} /></button></div></div></div><div className="mt-14"><SectionIntro eyebrow="ابدأ بما يهمك" title="محطات الدليل" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{knowledgeCards.map((title, index) => { const Icon = icons[index % icons.length]; return <button onClick={() => toast.info("المحتوى التفصيلي سيُضاف في مرحلة لاحقة من المنتج.")} key={title} className="group rounded-[22px] border border-[#e7e1d4] bg-white p-5 text-right transition hover:-translate-y-1 hover:border-[#d6b878] hover:shadow-[0_16px_30px_rgba(31,60,46,.08)]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eff5ef] text-[#0b7256]"><Icon size={19} /></span><h3 className="mt-6 font-display text-lg font-extrabold text-[#1d4338]">{title}</h3><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#9b7732]">اكتشف <ChevronLeft size={14} /></span></button>})}</div></div></section></AppChrome>; }
