/**
 * Style reminder — "رحلات من نور": offer details expose the source boundary first;
 * facts are large, unknowns stay unknown, and the original publisher is always one clear action away.
 */
import AppChrome, { BackLink, RouteTicket } from "@/components/AppChrome";
import { offers, formatDzd } from "@/lib/mockData";
import { BedDouble, Bus, CalendarDays, CircleAlert, ExternalLink, Hotel, Landmark, Plane, UsersRound } from "lucide-react";
import { useRoute } from "wouter";

export default function OfferDetails() {
  const [, params] = useRoute("/offer/:id");
  const offer = offers.find((item) => item.id === params?.id) ?? offers[0];
  const details = [[Plane,"مدينة الانطلاق",offer.route],[Hotel,"فندق مكة",offer.makkahHotel],[BedDouble,"فندق المدينة",offer.madinahHotel],[Bus,"نمط الرحلة",offer.transport],[CalendarDays,"المدة",offer.duration],[UsersRound,"نوع الغرفة",offer.room]];
  return <AppChrome><section className="container py-10 sm:py-14"><BackLink /><div className="mt-7 grid overflow-hidden rounded-[32px] border border-[#e4ded0] bg-white shadow-[0_18px_46px_rgba(32,55,43,.09)] lg:grid-cols-[.75fr_1.25fr]"><div className="relative min-h-[300px] overflow-hidden bg-[#064e3b] p-7 text-white"><span className="absolute -right-16 -top-20 h-56 w-80 rounded-[100%] border border-[#d6b878]/45" /><span className="absolute bottom-8 left-8 h-24 w-48 rounded-[100%] border border-white/15" /><div className="relative"><Landmark size={25} className="text-[#e3c775]" /><p className="mt-8 text-xs font-extrabold tracking-[.15em] text-[#e5cb87]">بطاقة مصدرية</p><h2 className="mt-3 font-display text-3xl font-extrabold leading-tight">كل معلومة هنا قابلة للعودة إلى مصدرها.</h2><p className="mt-4 text-sm leading-7 text-[#c7d9cf]">لا يضيف رفيق المعتمر تفاصيل غير منشورة، ولا يضمن التوفر أو السعر.</p></div></div><div className="p-6 sm:p-9"><RouteTicket route={offer.route} duration={offer.duration} /><h1 className="mt-5 font-display text-4xl font-extrabold leading-tight text-[#143f33]">{offer.title}</h1><p className="mt-3 max-w-xl text-sm leading-7 text-slate-600">{offer.description}</p><div className="mt-6 flex flex-wrap items-end justify-between gap-4 border-y border-[#eee9dd] py-5"><span><b className="block text-3xl font-extrabold tracking-tight text-[#07513e]" dir="ltr">{formatDzd(offer.price)}</b><small className="text-xs text-slate-500">السعر كما ظهر في المصدر</small></span><span className="rounded-2xl bg-[#eef6ef] px-4 py-2 text-xs font-bold text-[#137255]">تحقق: {offer.lastChecked}</span></div><a href={offer.sourceUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#064e3b] py-4 text-sm font-extrabold text-white transition hover:bg-[#0a674f]">فتح العرض في المصدر <ExternalLink size={17} /></a></div></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-[26px] border border-[#e8e2d5] bg-white p-6"><h2 className="font-display text-2xl font-extrabold text-[#153e32]">المعلومات المنشورة</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{details.map(([Icon, label, value]) => { const IconComponent = Icon as typeof Plane; return <div key={label as string} className="flex gap-3 rounded-2xl bg-[#f6f6f1] p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#e8f1eb] text-[#0a6d53]"><IconComponent size={18} /></span><span><b className="block text-xs text-[#29493f]">{label as string}</b><span className="mt-1 block text-sm text-slate-600">{value as string}</span></span></div>})}</div></section><aside className="space-y-5"><div className="rounded-[24px] bg-[#f0f5f0] p-5"><h2 className="font-display text-xl font-extrabold text-[#173e33]">سجل المصدر</h2><p className="mt-3 text-sm leading-7 text-[#4b655b]">{offer.sourceLabel}</p><p className="mt-1 text-xs text-slate-500">آخر تحقق في المنصة: {offer.lastChecked}</p></div><div className="rounded-[23px] border border-[#f0deb1] bg-[#fff7e4] p-5"><CircleAlert size={20} className="text-[#a97923]" /><h3 className="mt-3 font-bold text-[#64471b]">ملاحظة قبل اتخاذ القرار</h3><p className="mt-2 text-sm leading-6 text-[#80602a]">{offer.dataNote}</p></div></aside></div>
  </section></AppChrome>;
}
