/**
 * Style reminder — "رحلات من نور": the live-offer page puts source and date before conversion;
 * ivory space, gold route marks, and the official checkpoint make each choice feel traceable.
 */
import AppChrome, { RouteTicket, SectionIntro } from "@/components/AppChrome";
import OfferCard from "@/components/OfferCard";
import SourceTrustPanel from "@/components/SourceTrustPanel";
import { formatDzd, offers } from "@/lib/mockData";
import { CalendarDays, CircleAlert, ExternalLink, MapPin, Plane, SlidersHorizontal, Sparkles } from "lucide-react";

export default function Offers() {
  const featuredOffer = offers[0];
  const remainingOffers = offers.slice(1);
  return <AppChrome><section className="container py-12 sm:py-16"><SectionIntro eyebrow="عروض منشورة قابلة للرجوع للمصدر" title="عروض عمرة ظاهرة حاليًا" body="هذه القائمة تجمع ما ظهر في مصدر تجاري عام أثناء فحص 21 أغسطس 2026. لا تعني التوفر المضمون، ولا تمثل توصية مخصصة أو اعتمادًا للوكالة." action={<span className="inline-flex items-center gap-2 rounded-xl border border-[#d9d2c0] bg-white px-4 py-3 text-sm font-bold text-[#36594d]"><CalendarDays size={16} /> آخر تحقق: 21 أغسطس 2026</span>} />
    <SourceTrustPanel />
    <div className="mt-8 flex flex-wrap items-center gap-2 rounded-2xl bg-[#f0f3ee] p-2"><span className="inline-flex items-center gap-2 rounded-xl bg-[#064e3b] px-4 py-2.5 text-xs font-bold text-white"><SlidersHorizontal size={15} /> كل العروض المنشورة</span><span className="rounded-xl px-4 py-2.5 text-xs font-bold text-[#476156]">15 يومًا</span><span className="rounded-xl px-4 py-2.5 text-xs font-bold text-[#476156]">من 165,000 دج</span><span className="mr-auto px-2 text-xs font-bold text-slate-500">{offers.length} عروض في هذه المراجعة</span></div>
    <article className="journey-feature relative mt-7 overflow-hidden rounded-[32px] border border-[#e4cf94] bg-[#fffaf0] p-6 shadow-[0_16px_45px_rgba(93,68,22,.09)] sm:p-8"><span className="pointer-events-none absolute -left-24 -top-24 h-60 w-96 rounded-[100%] border border-[#d6b878]/70" /><span className="pointer-events-none absolute bottom-0 left-[12%] h-px w-[62%] bg-gradient-to-l from-transparent via-[#d6b878] to-transparent" /><div className="relative grid items-center gap-7 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-[25px] bg-[#064e3b] p-6 text-white"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-extrabold text-[#e9d188]"><Sparkles size={14} /> تذكرة مسار بارزة</span><div className="mt-6 grid h-16 w-16 place-items-center rounded-full border-2 border-[#d6b878] bg-[#0b614b] font-display text-lg font-extrabold text-[#f4dda0]">{featuredOffer.duration.replace(" يومًا", "")}</div><p className="mt-4 text-sm font-bold text-[#e3cb86]">المصدر راجع في {featuredOffer.lastChecked}</p><p className="mt-2 text-sm leading-7 text-[#c9d9d1]">عرضناه أولًا لأنه يجمع في بطاقة واحدة مدينة الانطلاق والمدة والسعر والرابط الأصلي؛ وليس لأنه توصية شخصية أو ضمان توفر.</p></div><div><p className="text-xs font-extrabold tracking-[.16em] text-[#9c762e]">أول محطة في المسار</p><h2 className="mt-3 font-display text-3xl font-extrabold leading-tight text-[#163f34]">{featuredOffer.title}</h2><div className="mt-5 flex flex-wrap items-center gap-3"><RouteTicket route={featuredOffer.route} duration={featuredOffer.duration} /><span className="inline-flex items-center gap-1.5 rounded-full border border-[#e2d4ac] bg-white px-3 py-1.5 text-xs font-bold text-[#6f5929]"><Plane size={13} /> {featuredOffer.transport}</span><span className="inline-flex items-center gap-1.5 rounded-full border border-[#e2d4ac] bg-white px-3 py-1.5 text-xs font-bold text-[#6f5929]"><MapPin size={13} /> سعر ظاهر</span></div><div className="mt-6 flex flex-wrap items-end justify-between gap-5 border-y border-[#eadfc7] py-5"><span><b className="block font-display text-4xl font-extrabold text-[#07523f]" dir="ltr">{formatDzd(featuredOffer.price)}</b><small className="text-xs text-slate-500">كما نشره المصدر</small></span><a href={featuredOffer.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-[#064e3b] px-4 py-3 text-sm font-extrabold text-white transition hover:bg-[#0b684f]">عرض المصدر الأصلي <ExternalLink size={16} /></a></div></div></div></article>
    <div className="route-divider mt-10" /><div className="mt-5 flex items-center justify-between"><p className="text-xs font-extrabold tracking-[.16em] text-[#9c762e]">محطات أخرى في نفس المراجعة</p><span className="text-xs text-slate-500">بطاقات مصدرية وليست توصيات مدفوعة</span></div><div className="mt-5 grid gap-5 lg:grid-cols-3">{remainingOffers.map((offer) => <OfferCard key={offer.id} offer={offer} />)}</div>
    <div className="mt-9 flex gap-3 rounded-2xl border border-[#ead9ad] bg-[#fff8e8] px-5 py-4 text-sm leading-7 text-[#755920]"><CircleAlert size={19} className="mt-1 shrink-0 text-[#a57c29]" /><p><b>قبل التواصل أو الدفع:</b> راجع الرابط الأصلي وتحقق من التوفر النهائي والبرنامج وشروط السعر والجهة المنظمة. الحقول غير المنشورة في المصدر بقيت ظاهرة كـ«غير مذكور» بدل استكمالها بالافتراض.</p></div>
  </section></AppChrome>;
}
