/** Data-backed route ticket: it never invents availability, ratings, or source details. */
import { ChevronLeft, Hotel, MapPin, Plane, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { formatArabicDate, formatDzd, MarketplaceOffer } from "@/lib/marketplace";
import { RouteTicket } from "./AppChrome";

export default function OfferCard({ offer, featured = false, score, onCompare, selected = false }: { offer: MarketplaceOffer; featured?: boolean; score?: number; onCompare?: () => void; selected?: boolean }) {
  const distance = offer.distanceToHaramMeters === null ? "المسافة غير منشورة" : `${offer.distanceToHaramMeters.toLocaleString("ar-DZ")} م عن الحرم`;
  return <article className={`group relative overflow-hidden rounded-[26px] border bg-white p-5 transition duration-300 hover:-translate-y-1 hover:shadow-[0_22px_48px_rgba(24,58,46,.13)] ${featured ? "border-[#d7bc7b] shadow-[0_16px_40px_rgba(83,64,23,.12)]" : "border-[#e6e2d7]"}`}>
    {featured && <div className="absolute inset-x-0 top-0 h-1.5 bg-gradient-to-l from-[#d6b878] via-[#f5e5ae] to-[#d6b878]" />}
    <div className="flex items-start justify-between gap-3 pt-1"><div><span className="inline-flex items-center gap-1 rounded-full bg-[#eef6f0] px-2.5 py-1 text-[11px] font-extrabold text-[#127355]"><ShieldCheck size={12} />وكالة ضمن المنصة</span><h3 className="mt-3 font-display text-xl font-extrabold leading-8 text-[#163f34]">{offer.title}</h3><p className="mt-1 text-xs font-bold text-[#6b8278]">{offer.agencyName}</p></div><div className="text-left"><span className="block text-xl font-extrabold tracking-tight text-[#0c4f3d]" dir="ltr">{formatDzd(offer.priceDzd)}</span><span className="text-[11px] text-slate-500">آخر تحديث {formatArabicDate(offer.priceUpdatedAt)}</span></div></div>
    <div className="mt-4"><RouteTicket route={`${offer.departureWilaya} ← جدة`} duration={`${offer.durationDays} أيام`} /></div>
    <div className="my-5 border-y border-dashed border-[#dfd5bf] py-4"><div className="grid grid-cols-2 gap-x-3 gap-y-3 text-xs text-[#496157]"><span className="flex items-center gap-1.5"><Hotel size={14} className="text-[#b48736]" />{offer.makkahHotel || "فندق مكة غير منشور"}</span><span className="flex items-center gap-1.5"><MapPin size={14} className="text-[#b48736]" />{distance}</span><span className="flex items-center gap-1.5"><Plane size={14} className="text-[#b48736]" />{offer.flightType === "direct" ? "رحلة مباشرة" : offer.flightType === "stopover" ? "رحلة بتوقف" : "نمط الرحلة غير منشور"}</span><span className="flex items-center gap-1.5"><UsersRound size={14} className="text-[#b48736]" />{offer.seatsAvailable === null ? "التوفر يُراجع مع الوكالة" : `${offer.seatsAvailable} مقاعد معلنة`}</span></div></div>
    {typeof score === "number" && <p className="mb-4 rounded-xl bg-[#f2f6ef] px-3 py-2 text-xs font-bold text-[#316252]">مطابقة مبدئية {score}% — مبنية على السعر والانطلاق والمدة ونمط الرحلة.</p>}
    <div className="flex items-center justify-between gap-3"><Link href={`/offer/${offer.id}`} className="inline-flex items-center gap-1 rounded-xl bg-[#073f31] px-3.5 py-2.5 text-xs font-bold text-white transition hover:bg-[#0b644e]">التفاصيل <ChevronLeft size={14} /></Link>{onCompare ? <button onClick={onCompare} className={`text-xs font-extrabold ${selected ? "text-[#9b742a]" : "text-[#0c7155]"}`}>{selected ? "إزالة من المقارنة" : "أضف للمقارنة"}</button> : <Link href={`/agencies/${offer.agencySlug}`} className="text-xs font-extrabold text-[#0c7155] hover:text-[#9c7731]">ملف الوكالة</Link>}</div>
  </article>;
}
