/**
 * Style reminder — "رحلات من نور": verification is presented as a warm, quiet checkpoint on the journey,
 * never as a claim of endorsement or a substitute for confirming travel terms with the source.
 */
import { ExternalLink, Landmark, ShieldCheck } from "lucide-react";

export default function SourceTrustPanel() {
  return <aside className="rounded-[24px] border border-[#d9e5dc] bg-[#eff5ef] p-5 sm:p-6"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div className="flex gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#064e3b] text-[#e5c979]"><ShieldCheck size={21} /></span><div><p className="text-sm font-extrabold text-[#174336]">مراجعة مصدرية قبل أي تواصل</p><p className="mt-1 max-w-2xl text-xs leading-6 text-[#50695e]">تمت مراجعة قائمة عروض ElOmraDZ في 21 أغسطس 2026. الأسعار والتوفر قد يتغيران، وظهور العرض هنا لا يعني اعتمادًا حكوميًا أو شراكة أو ضمانًا من رفيق المعتمر AI.</p></div></div><a href="http://marw.gov.dz/fr/%D9%85%D9%82%D8%A7%D9%84%D8%A7%D8%AA-%D9%88%D8%AF%D8%B1%D8%A7%D8%B3%D8%A7%D8%AA/hadj-et-omra" target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl border border-[#c8d8cd] bg-white px-4 py-3 text-xs font-bold text-[#135e48] hover:border-[#d6b878]"><Landmark size={15} /> مرجع الوزارة <ExternalLink size={14} /></a></div><div className="mt-5 flex flex-wrap gap-2 border-t border-[#d4e1d6] pt-4"><a href="https://bawabetelomra.dz/" target="_blank" rel="noreferrer" className="rounded-full bg-white px-3 py-2 text-xs font-bold text-[#31594c] hover:text-[#0b7457]">البوابة الجزائرية للعمرة ↗</a><a href="https://onpo.dz/" target="_blank" rel="noreferrer" className="rounded-full bg-white px-3 py-2 text-xs font-bold text-[#31594c] hover:text-[#0b7457]">الديوان الوطني للحج والعمرة ↗</a><a href="https://elomradz.com/" target="_blank" rel="noreferrer" className="rounded-full bg-white px-3 py-2 text-xs font-bold text-[#31594c] hover:text-[#0b7457]">قائمة العروض المصدرية ↗</a></div></aside>;
}
